version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 484010831236.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=484010831236.dkr.ecr.us-east-1.amazonaws.com/eternals
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"eternals","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json
